# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('type', models.CharField(max_length=10)),
                ('slug', models.SlugField()),
                ('link', models.URLField()),
                ('pub_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=63)),
                ('slug', models.SlugField()),
                ('text', models.TextField()),
                ('pub_date', models.DateField()),
            ],
        ),
    ]
